import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import useDevice from "../utils/hooks/useDevice";
import SignupSidebar from "../components/SignupSidebar";

export default function Home() {
  const { isTabletOrSmaller, isMobileOrSmaller } = useDevice();
  return (
    <div className={styles.container}>
      <Head>
        <title>Loch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.homepage_content}></div>
        {!isMobileOrSmaller && <SignupSidebar />}
      </main>
    </div>
  );
}
